export default Constraints = {
	//Home
	IRIS: 'IRIS',
	ENTER_PHONE_NUMBER: 'Enter phone number...',
	ENTER_YOUR_MESSAGE: 'Enter your message...',
	LOGIN: 'Login',
	SEARCH: 'Search...',
	title: 'IRIS AI',
	WAIT: 'Wait...',
	CANCEL: 'Cancel',
	YES: 'Yes',
	OK: 'Ok',
	SOMETHING: 'Something went wrong with image processing',
	PLEASE_CHOOSE_PIC: 'Choose your photo',
	GALLERY: 'Photos',
	HOW_WORK: 'How does this work?',
	SUBTITLE_AI: "I'm here to help! Ask me anything, and I'll do my best to provide information or assistance.",
	CAM: 'Camera',
	WELCOME: 'Welcome to AI chat',
	SETTINGS: 'Settings',
	PLEASE_FILL: 'Please fill credentials',
	ASK_MSG: 'Do you want to logout?',
	subTitle: 'AI Made Easy',
	ERROR_NETWORK: `⚠️ Oops! It seems there was a network error. 😟\n\nPlease check your internet connection and try again.`,
	ERROR_MESSAGE: `🤖 Oops! It seems I'm having trouble right now. 😟\n\nI apologize for the inconvenience. Please try again later or ask a different question. If the issue persists, feel free to contact support for assistance.`,
};
