export default Constraints = {
	//Home
	IRIS: 'IRIS',
	ENTER_PHONE_NUMBER: 'Enter phone number...',
	ENTER_YOUR_MESSAGE: 'Enter your message...',
	LOGIN: 'Login',
	SEARCH: 'Search...',
	title: 'IRIS AI',
	WAIT: 'Wait...',
	CANCEL: 'Cancel',
	YES: 'Yes',
	OK: 'Ok',
	SOMETHING: 'Something went wrong with image processing',
	PLEASE_CHOOSE_PIC: 'Choose your photo',
	GALLERY: 'Photos',
	HOW_WORK: "Let's get started!",
	SUBTITLE_AI:
		"How can I help you today? You can ask me to plan a detailed trip itinerary for you, send me a picture of your fridge and I'll give you recipe ideas, ask for shopping help to find the perfect product to buy for a gift, ask for advice, ask me to generate an image like a logo for your business, teach you how to do something, or whatever you can think of!",
	CAM: 'Camera',
	WELCOME: "Hello! I'm Iris, your AI personal assistant!",
	SETTINGS: 'Settings',
	PLEASE_FILL: 'Please fill credentials',
	ASK_MSG: 'Do you want to logout?',
	subTitle: 'AI Made Easy',
	ERROR_NETWORK: `⚠️ Oops! It seems there was a network error. 😟\n\nPlease check your internet connection and try again.`,
	ERROR_MESSAGE: `🤖 Oops! It seems I'm having trouble right now. 😟\n\nI apologize for the inconvenience. Please try again later or ask a different question. If the issue persists, feel free to contact support for assistance.`,
};
